name: tRNAgraph
channels:
  - conda-forge
  - bioconda
dependencies:
  - 'numpy'
  - 'pandas'
  - 'pyarrow'
  - 'scipy'
  - 'scikit-learn'
  - 'matplotlib'
  - 'seaborn'
  - 'anndata'
  - 'umap-learn'
  - 'hdbscan'
  - 'logomaker'
  - 'statannot'
  - 'jupyter'
  - 'jupyterlab>=4.0.12'