name: tRNAgraph
channels:
  - conda-forge
  - bioconda
dependencies:
  - 'python>=3.10'
  - 'git'
  - 'numpy'
  - 'pandas'
  - 'pyarrow'
  - 'scipy'
  - 'scikit-learn'
  - 'matplotlib'
  - 'seaborn=0.13.2'
  - 'anndata'
  - 'umap-learn'
  - 'hdbscan'
  - 'logomaker'