name: trnagraph
channels:
  - conda-forge
  - bioconda
dependencies:
  - "anndata=0.12.6"
  - "bedtools=2.31.1"
  - "bowtie2=2.5.4"
  - "fastp=1.0.1"
  - "gffpandas=1.2.2"
  - "gffread=0.12.7"
  - "git>=2.49.0"
  - "hdbscan=0.8.39"
  - "infernal=1.1.5"
  - "logomaker=0.8.6"
  - "matplotlib=3.9.1"
  - "numpy=2.3.5"
  - "pandas=2.3.3"
  - "pydeseq2=0.5.4"
  - "pysam=0.23.3"
  - "pysradb=2.5.1"
  - "python=3.12"
  - "samtools=1.22.1"
  - "scikit-learn=1.7.2"
  - "scipy=1.16.3"
  - "seaborn=0.13.2"
  - "sra-tools=3.2.1"
  - "typer=0.20.0"
  - "tqdm>=4.67.1"
  - "ucsc-bedgraphtobigwig=482"
  - "umap-learn=0.5.9.post2"
  - "umi_tools=1.1.6"
  - "venn=0.1.3"
