"""Complex Venns are enumerated in config, never generated by crossing axes.

The motivating case is four circles -- Day 0 and Day 70, each as full-length (o60) and as
fragments (u60) -- which crosses a grouping LEVEL with a read-length variant. Two more axes are
available (read type), and any of the three may be combined.

They are declared one set at a time rather than by naming axes to cross, because a product is
how a request for 45 circles happens by accident: three timepoints x three variants x five read
types. Enumerating makes the impossible request unexpressible instead of merely rejected.

This is also where `level` becomes reachable for the first time. `_set_members` filtered on
`spec.level_column`, a field VennSet never had -- unreachable while only the two automatic
diagrams existed, since neither sets a level, and an AttributeError the moment one did.
"""
import anndata as ad
import numpy as np
import pandas as pd

from trnagraph.modules import plotsVenn
from trnagraph.modules.toolsSchemas import MultivariateConfig


DECLARED = {
    'grouping': 'timepoint',
    'presence_cutoff': 1,
    'venn': [{
        'name': 'd0_d70_frag_full',
        'sets': [
            {'level': 'D0',  'variant': 'norm:o60'},
            {'level': 'D70', 'variant': 'norm:o60'},
            {'level': 'D0',  'variant': 'norm:u60'},
            {'level': 'D70', 'variant': 'norm:u60'},
        ],
    }],
}


def _adata():
    rows = []
    for level in ('D0', 'D70'):
        for replicate in range(2):
            for trna in ('tRNA-Ala-AGC-1', 'tRNA-Gly-GCC-1'):
                rows.append({'trna': trna, 'sample': f'{level}_{replicate}',
                             'timepoint': level, 'nreads_total_norm': 100.0})
    obs = pd.DataFrame(rows)
    obs.index = [f'o{i}' for i in range(len(obs))]
    adata = ad.AnnData(X=np.zeros((len(obs), 1), dtype='float32'), obs=obs)
    adata.uns['size_splits'] = {'u60': {}, 'o60': {}}
    # u60 carries only Gly; o60 carries both. So D0/D70 x u60/o60 has real structure.
    for tag, trnas in (('u60', {'tRNA-Gly-GCC-1'}), ('o60', {'tRNA-Ala-AGC-1', 'tRNA-Gly-GCC-1'})):
        adata.obsm[f'size_split_{tag}'] = pd.DataFrame(
            {'nreads_total_norm': [100.0 if t in trnas else 0.0 for t in obs['trna']]},
            index=obs.index)
    return adata


def test_a_declaration_becomes_a_plan_with_four_sets():
    block = MultivariateConfig.model_validate(DECLARED)

    plans = plotsVenn.declared_venn_plans(_adata(), block)

    assert [p.name for p in plans] == ['d0_d70_frag_full']
    assert len(plans[0].sets) == 4


def test_each_set_resolves_its_variant_to_a_tag_and_carries_its_level():
    block = MultivariateConfig.model_validate(DECLARED)

    sets = plotsVenn.declared_venn_plans(_adata(), block)[0].sets

    assert [s.tag for s in sets] == ['o60', 'o60', 'u60', 'u60']
    assert [s.level for s in sets] == ['D0', 'D70', 'D0', 'D70']
    assert {s.level_column for s in sets} == {'timepoint'}, 'taken from multivariate.grouping'


def test_labels_are_generated_from_what_distinguishes_the_sets():
    block = MultivariateConfig.model_validate(DECLARED)

    labels = [s.label for s in plotsVenn.declared_venn_plans(_adata(), block)[0].sets]

    assert len(set(labels)) == 4, 'four circles need four distinct labels'
    assert all('D0' in label or 'D70' in label for label in labels)


def test_membership_actually_honours_the_level():
    """The latent bug: _set_members filtered on spec.level_column, which VennSet never had."""
    adata = _adata()
    block = MultivariateConfig.model_validate(DECLARED)
    plan = plotsVenn.declared_venn_plans(adata, block)[0]

    members = {s.label: plotsVenn._set_members(adata, s, block.presence_cutoff) for s in plan.sets}

    o60_d0 = next(v for k, v in members.items() if 'D0' in k and 'o60' in k)
    u60_d0 = next(v for k, v in members.items() if 'D0' in k and 'u60' in k)
    assert o60_d0 == ['tRNA-Ala-AGC-1', 'tRNA-Gly-GCC-1']
    assert u60_d0 == ['tRNA-Gly-GCC-1'], 'u60 carries only Gly'
